# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  armDeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

#      - name: Deploy Resource Group rg-githubactions with AZ CLI
#        uses: Azure/cli@v1
#        with:
#          inlinescript: |
#            az deployment sub create --location "North Europe" --template-file ./arm-templates/resourcegroup.json  
            
      - name: Deploy Resource Group rg-githubactions
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: d18c27f6-f24c-4244-92e5-fbbf98355a16
          region: North Europe
          template: ./arm-templates/resourcegroup.json
          parameters:
            location="North Europe"
            resourceGroupName=rg-githubactions
          deploymentName: rg-githubactions
          
      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: d18c27f6-f24c-4244-92e5-fbbf98355a16
          template: ./arm-templates/storageaccount.json
          parameters: 
            #./arm-templates/storageaccount.parameters.json
            sku=Standard_LRS
            storageAccountName="globostg4442"
            location="West Europe"
          deploymentMode: incremental

      - run: echo ${{ steps.storageAccountDeploy.outputs.BlobUri }}


